# Generated by Django 5.1.6 on 2025-02-06 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carousel',
            name='description',
        ),
        migrations.AddField(
            model_name='carousel',
            name='quote',
            field=models.CharField(default=2, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='carousel',
            name='subtitle',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
