# Generated by Django 5.1.6 on 2025-02-06 14:46

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sanapp', '0004_faq_testimonial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='description',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='faq',
            name='answer',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='description',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='topdestination',
            name='description',
            field=tinymce.models.HTMLField(),
        ),
    ]
