# Generated by Django 5.1.6 on 2025-02-07 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanapp', '0005_alter_about_description_alter_faq_answer_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mission',
        ),
        migrations.DeleteModel(
            name='Vision',
        ),
        migrations.AddField(
            model_name='about',
            name='mission',
            field=models.CharField(default=9, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='about',
            name='vision',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
