# Generated by Django 5.1.6 on 2025-02-07 07:09

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sanapp', '0006_delete_mission_delete_vision_about_mission_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='about',
            name='mission',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='about',
            name='vision',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='topdestination',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
