# Generated by Django 5.1.6 on 2025-02-08 07:35

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanapp', '0007_alter_about_description_alter_about_mission_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', ckeditor.fields.RichTextField()),
                ('image', models.ImageField(upload_to='country/')),
            ],
        ),
        migrations.CreateModel(
            name='StudyCountry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', ckeditor.fields.RichTextField()),
                ('why_study', ckeditor.fields.RichTextField()),
                ('education_system', ckeditor.fields.RichTextField()),
                ('visa_process', ckeditor.fields.RichTextField()),
                ('work_permit', ckeditor.fields.RichTextField()),
                ('work_visa', ckeditor.fields.RichTextField()),
                ('choose_university', ckeditor.fields.RichTextField()),
                ('expenses', ckeditor.fields.RichTextField()),
                ('image', models.ImageField(upload_to='study_country/')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sanapp.country')),
            ],
        ),
    ]
