# Generated by Django 5.1.6 on 2025-02-09 05:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanapp', '0009_popularcourse'),
    ]

    operations = [
        migrations.AddField(
            model_name='popularcourse',
            name='country',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='sanapp.studycountry'),
            preserve_default=False,
        ),
    ]
