# Generated by Django 5.1.6 on 2025-02-09 12:42

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanapp', '0011_advertisement'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpertTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('position', models.CharField(max_length=200)),
                ('description', ckeditor.fields.RichTextField()),
                ('image', models.ImageField(upload_to='expert_team/')),
            ],
        ),
    ]
